# This software was developed at the National Institute of Standards
# and Technology by employees of the Federal Government in the course
# of their official duties. Pursuant to title 17 Section 105 of the
# United States Code this software is not subject to copyright
# protection and is in the public domain. NIST assumes no
# responsibility whatsoever for its use by other parties, and makes
# no guarantees, expressed or implied, about its quality,
# reliability, or any other characteristic.
#
# We would appreciate acknowledgement if the software is used.

# This workflow uses Make to confirm ontology files have been
# normalized according to the procedures in NORMALIZE.md.

name: Continuous Integration

on:
  push:
    branches: [ master, develop, pending-adoption ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository and all submodules to be able to properly build the case_monolithic.ttl file.
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Clean Build Artifacts
      run: make clean

    # Check both UCO and CASE so it properly builds the tests/case_monolithic.ttl
    - name: Run Tests
      run: |
        cd dependencies/UCO/
        make check
        cd ../../
        make check
    
    # Rename the file from the monolithic to a more consumable version
    - name: Rename File
      run: cp tests/case_monolithic.ttl ./case-0.5.0-$(date +%F).ttl && ls ./case-*

    # Upload the consolidated ontology into a TTL file that can be downloaded and used for validation purposes. 
    # The `make check` process creates a file in tests/case_monolithic.ttl. This file is then renamed and 
    # uploaded to GitHub as an artifact for easier consumption and adoption.
    - name: Upload CASE TTL File
      uses: actions/upload-artifact@v2
      with:
        name: case-ontology
        path: case-*.ttl
