name: Submodule Update

# Checks for updates to the submodules and re-points the submodule reference to the head of the specified branch
# Reference: https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
  push:
    branches: [ master, develop, pending-adoption ]

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.CI_TOKEN }}
        submodules: 'recursive'

    # Update references
    - name: Git Submodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive
        cd dependencies/UCO
        git fetch
        git checkout pending-adoption
        git pull
        cd ../..

    - name: Commit update
      run: |
        git config --global user.name 'Submodule Update Bot'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"
